import{a as S,S as q,i as l}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const P="57589880-91d2feb9d1ddc011e9b4ff177",M="https://pixabay.com/api/";async function m(o,t){return(await S.get(M,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector("#load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function B(){p.innerHTML=""}function g(){d&&d.classList.add("is-visible")}function y(){d&&d.classList.remove("is-visible")}function h(){u&&u.classList.remove("is-hidden")}function f(){u&&u.classList.add("is-hidden")}function b(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:a,comments:w,downloads:v})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${i}" alt="${e}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${r}</p>
            <p class="info-item"><b>Views</b> ${a}</p>
            <p class="info-item"><b>Comments</b> ${w}</p>
            <p class="info-item"><b>Downloads</b> ${v}</p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",t),$.refresh()}const E=document.querySelector(".form"),O=document.querySelector("#load-more");let c="",n=1;E.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),c===""){l.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}n=1,B(),f(),g();try{const t=await m(c,n);if(t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(t.hits),t.totalHits>15&&h()}catch{L()}finally{y()}});O.addEventListener("click",async()=>{n+=1,f(),g();try{const o=await m(c,n);b(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}const i=Math.ceil(o.totalHits/15);n>=i?(f(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):h()}catch{L()}finally{y()}});function L(){l.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}
//# sourceMappingURL=index.js.map
